# .github/workflows/release.yml

name: Build & Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:ci

      - name: Prepare Artifacts for Upload
        run: |
          mkdir artifact
          move dist\*.exe artifact\
          move dist\*.yml artifact\
          if exist dist\*.blockmap move dist\*.blockmap artifact\
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: artifact/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap
